<!-- 全局图标控制 -->
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="iconAdd" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page_add.png"/>
<c:set var="iconEdit" value="${pageContext.request.contextPath}/resources/spk_resource/image/extjs_icons/pencil.png"/>
<c:set var="iconDelete" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page_delete.png"/>
<c:set var="iconBack" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/back.png"/>
<c:set var="iconCancel" value="${pageContext.request.contextPath}/resources/spk_resource/image/extjs_icons/cancel.png"/>
<c:set var="iconCut" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/cut.png"/>
<c:set var="iconFilter" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/filter.png"/>
<c:set var="iconHelp" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/help.png"/>
<c:set var="iconOk" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/ok.png"/>
<c:set var="iconError" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/error.png"/>
<c:set var="iconExcel" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page_excel.png"/>
<c:set var="iconFind" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page_find.png"/>
<c:set var="iconRefresh" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page_refresh.png"/>
<c:set var="iconSave" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/disk.png"/>
<c:set var="iconPrint" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/print.png"/>
<c:set var="iconRedo" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/redo.png"/>
<c:set var="iconSum" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/sum.png"/>
<c:set var="iconTip" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/tip.png"/>
<c:set var="iconUndo" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/undo.png"/>
<c:set var="iconUserAdd" value="${pageContext.request.contextPath}/resources/spk_resource/image/extjs_icons/key.png"/>
<c:set var="iconGroupAdd" value="${pageContext.request.contextPath}/resources/spk_resource/image/extjs_icons/group/group_add.png"/>
<c:set var="iconGo" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page_go.png"/>
<c:set var="iconLink" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page_link.png"/>
<c:set var="iconScript" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/script.png"/>
<c:set var="iconUpload" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/attachment.png"/>
<c:set var="iconFind1" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/application-form-magnify.png"/>
<c:set var="iconSet" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/settings.png"/>
<c:set var="iconConfig" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/config.png"/>
<c:set var="iconAddUser" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/user-add.png"/>
<c:set var="iconGroupDelete" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/group-delete.png"/>
<c:set var="iconLook" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/zoom.png"/>
<c:set var="iconAuth" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page-key.png"/>
<c:set var="iconPackageUpload" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/sign-up.png"/>
<c:set var="iconVersionSet" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page-white-gear.png"/>
<c:set var="iconAddressList" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/report-magnify.png"/>
<c:set var="iconEye" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/eye.png"/>
<c:set var="iconRemove2" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/remove2.png"/>
<c:set var="iconGroupLink" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/group-link.png"/>
<c:set var="iconScriptSet" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/script-gear.png"/>
<c:set var="iconWorld" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/world.png"/>
<c:set var="iconLink" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/link.png"/>
<c:set var="iconGroupGear" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/group-gear.png"/>
<c:set var="iconGroupKey" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/group-key.png"/>
<c:set var="iconPageGear" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/page-gear.png"/>
<c:set var="iconUndo2" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/undo2.png"/>
<c:set var="iconForward" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/forward.png"/>
<c:set var="iconPush" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/push2.png"/>
<c:set var="iconDownload" value="${pageContext.request.contextPath}/resources/spk_resource/image/icons/download.png"/>

